// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldEncryptionKey holds the string denoting the encryption_key field in the database.
	FieldEncryptionKey = "encryption_key"
	// FieldMedID holds the string denoting the med_id field in the database.
	FieldMedID = "med_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// EdgeChips holds the string denoting the chips edge name in mutations.
	EdgeChips = "chips"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ChipsTable is the table that holds the chips relation/edge.
	ChipsTable = "chips"
	// ChipsInverseTable is the table name for the Chip entity.
	// It exists in this package in order to avoid circular dependency with the "chip" package.
	ChipsInverseTable = "chips"
	// ChipsColumn is the table column denoting the chips relation/edge.
	ChipsColumn = "user_chips"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
	FieldPhoneNumber,
	FieldEncryptionKey,
	FieldMedID,
	FieldRole,
	FieldData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleUser     Role = "user"
	RoleEmployee Role = "employee"
	RoleAdmin    Role = "admin"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleUser, RoleEmployee, RoleAdmin:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByPhoneNumber orders the results by the phone_number field.
func ByPhoneNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumber, opts...).ToFunc()
}

// ByEncryptionKey orders the results by the encryption_key field.
func ByEncryptionKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptionKey, opts...).ToFunc()
}

// ByMedID orders the results by the med_id field.
func ByMedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByChipsCount orders the results by chips count.
func ByChipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChipsStep(), opts...)
	}
}

// ByChips orders the results by chips terms.
func ByChips(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChipsTable, ChipsColumn),
	)
}
