// Code generated by ent, DO NOT EDIT.

package meduser

import (
	"viseh-api/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldPassword, v))
}

// PhoneNumber applies equality check predicate on the "phone_number" field. It's identical to PhoneNumberEQ.
func PhoneNumber(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldPhoneNumber, v))
}

// Organisation applies equality check predicate on the "organisation" field. It's identical to OrganisationEQ.
func Organisation(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldOrganisation, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContainsFold(FieldPassword, v))
}

// PhoneNumberEQ applies the EQ predicate on the "phone_number" field.
func PhoneNumberEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldPhoneNumber, v))
}

// PhoneNumberNEQ applies the NEQ predicate on the "phone_number" field.
func PhoneNumberNEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldPhoneNumber, v))
}

// PhoneNumberIn applies the In predicate on the "phone_number" field.
func PhoneNumberIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldPhoneNumber, vs...))
}

// PhoneNumberNotIn applies the NotIn predicate on the "phone_number" field.
func PhoneNumberNotIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldPhoneNumber, vs...))
}

// PhoneNumberGT applies the GT predicate on the "phone_number" field.
func PhoneNumberGT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldPhoneNumber, v))
}

// PhoneNumberGTE applies the GTE predicate on the "phone_number" field.
func PhoneNumberGTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldPhoneNumber, v))
}

// PhoneNumberLT applies the LT predicate on the "phone_number" field.
func PhoneNumberLT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldPhoneNumber, v))
}

// PhoneNumberLTE applies the LTE predicate on the "phone_number" field.
func PhoneNumberLTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldPhoneNumber, v))
}

// PhoneNumberContains applies the Contains predicate on the "phone_number" field.
func PhoneNumberContains(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContains(FieldPhoneNumber, v))
}

// PhoneNumberHasPrefix applies the HasPrefix predicate on the "phone_number" field.
func PhoneNumberHasPrefix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasPrefix(FieldPhoneNumber, v))
}

// PhoneNumberHasSuffix applies the HasSuffix predicate on the "phone_number" field.
func PhoneNumberHasSuffix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasSuffix(FieldPhoneNumber, v))
}

// PhoneNumberEqualFold applies the EqualFold predicate on the "phone_number" field.
func PhoneNumberEqualFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEqualFold(FieldPhoneNumber, v))
}

// PhoneNumberContainsFold applies the ContainsFold predicate on the "phone_number" field.
func PhoneNumberContainsFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContainsFold(FieldPhoneNumber, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldRole, vs...))
}

// OrganisationEQ applies the EQ predicate on the "organisation" field.
func OrganisationEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEQ(FieldOrganisation, v))
}

// OrganisationNEQ applies the NEQ predicate on the "organisation" field.
func OrganisationNEQ(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNEQ(FieldOrganisation, v))
}

// OrganisationIn applies the In predicate on the "organisation" field.
func OrganisationIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldIn(FieldOrganisation, vs...))
}

// OrganisationNotIn applies the NotIn predicate on the "organisation" field.
func OrganisationNotIn(vs ...string) predicate.MedUser {
	return predicate.MedUser(sql.FieldNotIn(FieldOrganisation, vs...))
}

// OrganisationGT applies the GT predicate on the "organisation" field.
func OrganisationGT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGT(FieldOrganisation, v))
}

// OrganisationGTE applies the GTE predicate on the "organisation" field.
func OrganisationGTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldGTE(FieldOrganisation, v))
}

// OrganisationLT applies the LT predicate on the "organisation" field.
func OrganisationLT(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLT(FieldOrganisation, v))
}

// OrganisationLTE applies the LTE predicate on the "organisation" field.
func OrganisationLTE(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldLTE(FieldOrganisation, v))
}

// OrganisationContains applies the Contains predicate on the "organisation" field.
func OrganisationContains(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContains(FieldOrganisation, v))
}

// OrganisationHasPrefix applies the HasPrefix predicate on the "organisation" field.
func OrganisationHasPrefix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasPrefix(FieldOrganisation, v))
}

// OrganisationHasSuffix applies the HasSuffix predicate on the "organisation" field.
func OrganisationHasSuffix(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldHasSuffix(FieldOrganisation, v))
}

// OrganisationEqualFold applies the EqualFold predicate on the "organisation" field.
func OrganisationEqualFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldEqualFold(FieldOrganisation, v))
}

// OrganisationContainsFold applies the ContainsFold predicate on the "organisation" field.
func OrganisationContainsFold(v string) predicate.MedUser {
	return predicate.MedUser(sql.FieldContainsFold(FieldOrganisation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MedUser) predicate.MedUser {
	return predicate.MedUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MedUser) predicate.MedUser {
	return predicate.MedUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MedUser) predicate.MedUser {
	return predicate.MedUser(sql.NotPredicates(p))
}
