// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"viseh-api/database/ent/key"
	"viseh-api/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeyUpdate is the builder for updating Key entities.
type KeyUpdate struct {
	config
	hooks    []Hook
	mutation *KeyMutation
}

// Where appends a list predicates to the KeyUpdate builder.
func (ku *KeyUpdate) Where(ps ...predicate.Key) *KeyUpdate {
	ku.mutation.Where(ps...)
	return ku
}

// SetKey sets the "key" field.
func (ku *KeyUpdate) SetKey(s string) *KeyUpdate {
	ku.mutation.SetKey(s)
	return ku
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (ku *KeyUpdate) SetNillableKey(s *string) *KeyUpdate {
	if s != nil {
		ku.SetKey(*s)
	}
	return ku
}

// Mutation returns the KeyMutation object of the builder.
func (ku *KeyUpdate) Mutation() *KeyMutation {
	return ku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ku *KeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ku.sqlSave, ku.mutation, ku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ku *KeyUpdate) SaveX(ctx context.Context) int {
	affected, err := ku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ku *KeyUpdate) Exec(ctx context.Context) error {
	_, err := ku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ku *KeyUpdate) ExecX(ctx context.Context) {
	if err := ku.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ku *KeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(key.Table, key.Columns, sqlgraph.NewFieldSpec(key.FieldID, field.TypeString))
	if ps := ku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ku.mutation.Key(); ok {
		_spec.SetField(key.FieldKey, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ku.mutation.done = true
	return n, nil
}

// KeyUpdateOne is the builder for updating a single Key entity.
type KeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeyMutation
}

// SetKey sets the "key" field.
func (kuo *KeyUpdateOne) SetKey(s string) *KeyUpdateOne {
	kuo.mutation.SetKey(s)
	return kuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (kuo *KeyUpdateOne) SetNillableKey(s *string) *KeyUpdateOne {
	if s != nil {
		kuo.SetKey(*s)
	}
	return kuo
}

// Mutation returns the KeyMutation object of the builder.
func (kuo *KeyUpdateOne) Mutation() *KeyMutation {
	return kuo.mutation
}

// Where appends a list predicates to the KeyUpdate builder.
func (kuo *KeyUpdateOne) Where(ps ...predicate.Key) *KeyUpdateOne {
	kuo.mutation.Where(ps...)
	return kuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (kuo *KeyUpdateOne) Select(field string, fields ...string) *KeyUpdateOne {
	kuo.fields = append([]string{field}, fields...)
	return kuo
}

// Save executes the query and returns the updated Key entity.
func (kuo *KeyUpdateOne) Save(ctx context.Context) (*Key, error) {
	return withHooks(ctx, kuo.sqlSave, kuo.mutation, kuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (kuo *KeyUpdateOne) SaveX(ctx context.Context) *Key {
	node, err := kuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (kuo *KeyUpdateOne) Exec(ctx context.Context) error {
	_, err := kuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kuo *KeyUpdateOne) ExecX(ctx context.Context) {
	if err := kuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (kuo *KeyUpdateOne) sqlSave(ctx context.Context) (_node *Key, err error) {
	_spec := sqlgraph.NewUpdateSpec(key.Table, key.Columns, sqlgraph.NewFieldSpec(key.FieldID, field.TypeString))
	id, ok := kuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Key.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := kuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, key.FieldID)
		for _, f := range fields {
			if !key.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != key.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := kuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := kuo.mutation.Key(); ok {
		_spec.SetField(key.FieldKey, field.TypeString, value)
	}
	_node = &Key{config: kuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, kuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	kuo.mutation.done = true
	return _node, nil
}
