// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"viseh-api/database/ent/meduser"
	"viseh-api/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MedUserDelete is the builder for deleting a MedUser entity.
type MedUserDelete struct {
	config
	hooks    []Hook
	mutation *MedUserMutation
}

// Where appends a list predicates to the MedUserDelete builder.
func (mud *MedUserDelete) Where(ps ...predicate.MedUser) *MedUserDelete {
	mud.mutation.Where(ps...)
	return mud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mud *MedUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mud.sqlExec, mud.mutation, mud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mud *MedUserDelete) ExecX(ctx context.Context) int {
	n, err := mud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mud *MedUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(meduser.Table, sqlgraph.NewFieldSpec(meduser.FieldID, field.TypeInt))
	if ps := mud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mud.mutation.done = true
	return affected, err
}

// MedUserDeleteOne is the builder for deleting a single MedUser entity.
type MedUserDeleteOne struct {
	mud *MedUserDelete
}

// Where appends a list predicates to the MedUserDelete builder.
func (mudo *MedUserDeleteOne) Where(ps ...predicate.MedUser) *MedUserDeleteOne {
	mudo.mud.mutation.Where(ps...)
	return mudo
}

// Exec executes the deletion query.
func (mudo *MedUserDeleteOne) Exec(ctx context.Context) error {
	n, err := mudo.mud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{meduser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mudo *MedUserDeleteOne) ExecX(ctx context.Context) {
	if err := mudo.Exec(ctx); err != nil {
		panic(err)
	}
}
