// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"viseh-api/database/ent/meduser"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MedUserCreate is the builder for creating a MedUser entity.
type MedUserCreate struct {
	config
	mutation *MedUserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (muc *MedUserCreate) SetName(s string) *MedUserCreate {
	muc.mutation.SetName(s)
	return muc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muc *MedUserCreate) SetNillableName(s *string) *MedUserCreate {
	if s != nil {
		muc.SetName(*s)
	}
	return muc
}

// SetEmail sets the "email" field.
func (muc *MedUserCreate) SetEmail(s string) *MedUserCreate {
	muc.mutation.SetEmail(s)
	return muc
}

// SetPassword sets the "password" field.
func (muc *MedUserCreate) SetPassword(s string) *MedUserCreate {
	muc.mutation.SetPassword(s)
	return muc
}

// SetPhoneNumber sets the "phone_number" field.
func (muc *MedUserCreate) SetPhoneNumber(s string) *MedUserCreate {
	muc.mutation.SetPhoneNumber(s)
	return muc
}

// SetRole sets the "role" field.
func (muc *MedUserCreate) SetRole(m meduser.Role) *MedUserCreate {
	muc.mutation.SetRole(m)
	return muc
}

// SetOrganisation sets the "organisation" field.
func (muc *MedUserCreate) SetOrganisation(s string) *MedUserCreate {
	muc.mutation.SetOrganisation(s)
	return muc
}

// Mutation returns the MedUserMutation object of the builder.
func (muc *MedUserCreate) Mutation() *MedUserMutation {
	return muc.mutation
}

// Save creates the MedUser in the database.
func (muc *MedUserCreate) Save(ctx context.Context) (*MedUser, error) {
	muc.defaults()
	return withHooks(ctx, muc.sqlSave, muc.mutation, muc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (muc *MedUserCreate) SaveX(ctx context.Context) *MedUser {
	v, err := muc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (muc *MedUserCreate) Exec(ctx context.Context) error {
	_, err := muc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muc *MedUserCreate) ExecX(ctx context.Context) {
	if err := muc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muc *MedUserCreate) defaults() {
	if _, ok := muc.mutation.Name(); !ok {
		v := meduser.DefaultName
		muc.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muc *MedUserCreate) check() error {
	if _, ok := muc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MedUser.name"`)}
	}
	if v, ok := muc.mutation.Name(); ok {
		if err := meduser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MedUser.name": %w`, err)}
		}
	}
	if _, ok := muc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "MedUser.email"`)}
	}
	if v, ok := muc.mutation.Email(); ok {
		if err := meduser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "MedUser.email": %w`, err)}
		}
	}
	if _, ok := muc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "MedUser.password"`)}
	}
	if _, ok := muc.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "MedUser.phone_number"`)}
	}
	if _, ok := muc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "MedUser.role"`)}
	}
	if v, ok := muc.mutation.Role(); ok {
		if err := meduser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "MedUser.role": %w`, err)}
		}
	}
	if _, ok := muc.mutation.Organisation(); !ok {
		return &ValidationError{Name: "organisation", err: errors.New(`ent: missing required field "MedUser.organisation"`)}
	}
	return nil
}

func (muc *MedUserCreate) sqlSave(ctx context.Context) (*MedUser, error) {
	if err := muc.check(); err != nil {
		return nil, err
	}
	_node, _spec := muc.createSpec()
	if err := sqlgraph.CreateNode(ctx, muc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	muc.mutation.id = &_node.ID
	muc.mutation.done = true
	return _node, nil
}

func (muc *MedUserCreate) createSpec() (*MedUser, *sqlgraph.CreateSpec) {
	var (
		_node = &MedUser{config: muc.config}
		_spec = sqlgraph.NewCreateSpec(meduser.Table, sqlgraph.NewFieldSpec(meduser.FieldID, field.TypeInt))
	)
	if value, ok := muc.mutation.Name(); ok {
		_spec.SetField(meduser.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := muc.mutation.Email(); ok {
		_spec.SetField(meduser.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := muc.mutation.Password(); ok {
		_spec.SetField(meduser.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := muc.mutation.PhoneNumber(); ok {
		_spec.SetField(meduser.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := muc.mutation.Role(); ok {
		_spec.SetField(meduser.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := muc.mutation.Organisation(); ok {
		_spec.SetField(meduser.FieldOrganisation, field.TypeString, value)
		_node.Organisation = value
	}
	return _node, _spec
}

// MedUserCreateBulk is the builder for creating many MedUser entities in bulk.
type MedUserCreateBulk struct {
	config
	err      error
	builders []*MedUserCreate
}

// Save creates the MedUser entities in the database.
func (mucb *MedUserCreateBulk) Save(ctx context.Context) ([]*MedUser, error) {
	if mucb.err != nil {
		return nil, mucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mucb.builders))
	nodes := make([]*MedUser, len(mucb.builders))
	mutators := make([]Mutator, len(mucb.builders))
	for i := range mucb.builders {
		func(i int, root context.Context) {
			builder := mucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MedUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mucb *MedUserCreateBulk) SaveX(ctx context.Context) []*MedUser {
	v, err := mucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mucb *MedUserCreateBulk) Exec(ctx context.Context) error {
	_, err := mucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mucb *MedUserCreateBulk) ExecX(ctx context.Context) {
	if err := mucb.Exec(ctx); err != nil {
		panic(err)
	}
}
