// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chip is the predicate function for chip builders.
type Chip func(*sql.Selector)

// Key is the predicate function for key builders.
type Key func(*sql.Selector)

// MedUser is the predicate function for meduser builders.
type MedUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
